# Generated by Django 4.1.2 on 2022-10-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Botilleria', '0004_remove_cartproducts_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartProducts',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
