# Generated by Django 4.1.2 on 2022-10-24 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Botilleria', '0007_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
