# Generated by Django 4.1.2 on 2022-11-17 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Botilleria', '0010_alter_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchased_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Botilleria.product')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Botilleria.product')),
                ('purchase_product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Botilleria.purchased_products')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='purchased_products',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Botilleria.user'),
        ),
        migrations.CreateModel(
            name='Purchase_invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Botilleria.product')),
                ('purchase_product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Botilleria.purchased_products')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
