# Generated by Django 4.1.2 on 2022-11-17 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Botilleria', '0011_purchased_products_user_ticket_purchase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchased_products',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='purchased_products',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='ticket_purchase',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='ticket_purchase',
            name='purchase_product_id',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Purchase_invoice',
        ),
        migrations.DeleteModel(
            name='Purchased_products',
        ),
        migrations.DeleteModel(
            name='Ticket_purchase',
        ),
    ]
