# Generated by Django 4.1.2 on 2022-11-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Botilleria', '0012_remove_purchased_products_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='admin', max_length=50),
            preserve_default=False,
        ),
    ]
