# Generated by Django 4.1.2 on 2022-11-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Botilleria', '0016_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
