# Generated by Django 4.1.2 on 2022-11-27 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Botilleria', '0022_rename_username_user_username_field_user_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username_field',
            new_name='username',
        ),
    ]
