# Generated by Django 4.1.2 on 2022-11-27 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Botilleria', '0023_rename_username_field_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
