# Generated by Django 4.1.4 on 2022-12-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Botilleria', '0025_purchased_products_ticket_purchase_purchase_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchased_products',
            name='purchase_code',
            field=models.CharField(default='23', max_length=50),
            preserve_default=False,
        ),
    ]
