# Generated by Django 4.1.4 on 2023-12-10 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Botilleria', '0027_product_min_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchased_products',
            name='product_id',
        ),
        migrations.AddField(
            model_name='purchased_products',
            name='product_id',
            field=models.ManyToManyField(to='Botilleria.product'),
        ),
    ]
