# Generated by Django 4.1.4 on 2023-12-10 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Botilleria', '0028_remove_purchased_products_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchased_products',
            name='product_id',
        ),
        migrations.AddField(
            model_name='purchased_products',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Botilleria.product'),
        ),
    ]
